# Generated by Django 2.2.7 on 2019-11-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.FloatField(help_text='Longitude')),
                ('Y', models.FloatField(help_text='Latitude')),
                ('unique_squirrel_id', models.CharField(help_text='Squirrel ID', max_length=100)),
                ('Shift', models.CharField(choices=[('pm', 'PM'), ('am', 'AM')], help_text='Shift', max_length=5)),
                ('date', models.DateField(help_text='Date')),
                ('age', models.CharField(choices=[('adult', 'Adult'), ('juvenile', 'Juvenile'), ('', 'N/A')], default='', help_text='Age', max_length=20)),
                ('primary_fur_color', models.CharField(choices=[('black', 'Black'), ('gray', 'Gray'), ('cinnamon', 'Cinnamon'), ('', 'N/A')], default='', help_text='Primary Fur Color', max_length=20)),
                ('location', models.CharField(choices=[('above ground', 'Above Ground'), ('ground plane', 'Ground Plane'), ('', 'N/A')], default='', help_text='Location', max_length=50)),
                ('specific', models.CharField(help_text='Specific Location', max_length=100)),
                ('running', models.CharField(choices=[('true', 'True'), ('false', 'False')], help_text='Running', max_length=20)),
                ('chasing', models.CharField(choices=[('true', 'True'), ('false', 'False')], help_text='Chasing', max_length=20)),
                ('climbing', models.CharField(choices=[('true', 'True'), ('false', 'False')], help_text='Climbing', max_length=20)),
                ('eating', models.CharField(choices=[('true', 'True'), ('false', 'False')], help_text='Eating', max_length=20)),
                ('foraging', models.CharField(choices=[('true', 'True'), ('false', 'False')], help_text='Foraging', max_length=20)),
                ('other_activities', models.CharField(help_text='Other Activities', max_length=100)),
                ('kuks', models.CharField(choices=[('true', 'True'), ('false', 'False')], help_text='Kuks', max_length=20)),
                ('quaas', models.CharField(choices=[('true', 'True'), ('false', 'False')], help_text='Quaas', max_length=20)),
                ('moans', models.CharField(choices=[('true', 'True'), ('false', 'False')], help_text='Moans', max_length=20)),
                ('tail_flags', models.CharField(choices=[('true', 'True'), ('false', 'False')], help_text='Tail flags', max_length=20)),
                ('tail_twitches', models.CharField(choices=[('true', 'True'), ('false', 'False')], help_text='Tail twitches', max_length=20)),
                ('approaches', models.CharField(choices=[('true', 'True'), ('false', 'False')], help_text='Approaches', max_length=20)),
                ('indifferent', models.CharField(choices=[('true', 'True'), ('false', 'False')], help_text='Indifferent', max_length=20)),
                ('runs_from', models.CharField(choices=[('true', 'True'), ('false', 'False')], help_text='Runs from', max_length=20)),
            ],
        ),
    ]
