# Generated by Django 2.2.7 on 2019-11-29 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrel',
            old_name='Y',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='X',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='specific',
            new_name='specific_location',
        ),
    ]
