# Generated by Django 2.2.7 on 2019-11-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20191129_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Shift',
            field=models.CharField(choices=[('pm', 'PM'), ('am', 'AM')], default='am', help_text='Shift', max_length=5),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='age',
            field=models.CharField(choices=[('adult', 'Adult'), ('juvenile', 'Juvenile'), ('', 'N/A')], default='adult', help_text='Age', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='approaches',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', help_text='Approaches', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='chasing',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', help_text='Chasing', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='climbing',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', help_text='Climbing', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='eating',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', help_text='Eating', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='foraging',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', help_text='Foraging', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='indifferent',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', help_text='Indifferent', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='kuks',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', help_text='Kuks', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='location',
            field=models.CharField(choices=[('above ground', 'Above Ground'), ('ground plane', 'Ground Plane'), ('', 'N/A')], default='above ground', help_text='Location', max_length=50),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='moans',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', help_text='Moans', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='primary_fur_color',
            field=models.CharField(choices=[('black', 'Black'), ('gray', 'Gray'), ('cinnamon', 'Cinnamon'), ('', 'N/A')], default='black', help_text='Primary Fur Color', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='quaas',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', help_text='Quaas', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='running',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', help_text='Running', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='runs_from',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', help_text='Runs from', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='tail_flags',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', help_text='Tail flags', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='tail_twitches',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', help_text='Tail twitches', max_length=20),
        ),
    ]
