# Generated by Django 2.2.7 on 2019-11-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0005_auto_20191129_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='unique_squirrel_id',
            field=models.CharField(help_text='Squirrel ID', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
