# Generated by Django 2.2.7 on 2019-12-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0010_auto_20191209_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='climbing',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', max_length=20),
        ),
    ]
